[workspace]
resolver = "2"
members = [
    "crates/compiler",
    "crates/runtime",
    "crates/godot_bind",
]

[workspace.package]
version = "0.0.2"
edition = "2021"
authors = ["FerrisScript Contributors"]
license = "MIT"

[workspace.dependencies]
criterion = "0.5"
