[package]
name = "ferrisscript_runtime"
version = "0.0.3"
edition = "2021"

[dependencies]
ferrisscript_compiler = { path = "../compiler" }

[dev-dependencies]
criterion = { workspace = true }
ferrisscript_compiler = { path = "../compiler" }

[[bench]]
name = "runtime_benchmarks"
harness = false
