[package]
name = "rustyscript_godot_bind"
version = "0.0.1"
edition = "2021"

[dependencies]
# gdext is the Godot 4.x Rust binding (formerly gdextension)
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
rustyscript_compiler = { path = "../compiler" }
rustyscript_runtime = { path = "../runtime" }

[lib]
crate-type = ["cdylib"]
