[package]
name = "rustyscript_godot_bind"
version = "0.0.1"
edition = "2021"

[dependencies]
# gdext is the Godot 4.x Rust binding (formerly gdextension)
# Using version 0.1 which is compatible with Godot 4.2+
godot = "0.1"
rustyscript_compiler = { path = "../compiler" }
rustyscript_runtime = { path = "../runtime" }

[lib]
crate-type = ["cdylib"]
