name: Documentation Linting

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/docs-lint.yml'
      - '.markdownlint.json'
      - '.markdown-link-check.json'
  push:
    branches: 
      - main
      - develop
    paths:
      - '**.md'
      - 'docs/**'

jobs:
  markdown-lint:
    name: Markdown Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run markdownlint
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .markdownlint.json

  link-check:
    name: Markdown Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find markdown files (excluding archive)
        id: find-files
        run: |
          FILES=$(find . -name "*.md" -not -path "./docs/archive/*" -not -path "./target/*" -not -path "./node_modules/*" | tr '\n' ',')
          echo "files=${FILES%,}" >> $GITHUB_OUTPUT

      - name: Check markdown links
        if: steps.find-files.outputs.files != ''
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: '.markdown-link-check.json'
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
          file-path: ${{ steps.find-files.outputs.files }}
